require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from:
  - .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 3.1

# Until https://github.com/rubocop/rubocop/issues/10605
Style/RedundantCondition:
  Exclude:
    - 'app/workers/run_thread_manager.rb'
