require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
inherit_from:
  - .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 3.4
