require:
  - rubocop-performance
  - rubocop-rails
inherit_from:
    - .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb

# Until https://github.com/rubocop-hq/rubocop/issues/6893
Naming/RescuedExceptionsVariableName:
  Exclude:
    - 'app/server/managers/html_result_manager.rb'
