require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from:
  - .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 3.1
