require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from:
    - .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable

# Until https://github.com/rubocop/rubocop-rspec/issues/1160
RSpec/Rails/AvoidSetupHook:
  Enabled: false
