linters:
    ColorVariable:
        enabled: false
    MergeableSelector:
        enabled: false
    QualifyingElement:
        enabled: false
    SelectorFormat:
        enabled: false
    VendorPrefix:
        enabled: false
    IdSelector:
        enabled: false
    ImportantRule:
        enabled: false
