language: ruby
services:
  - docker
  - postgresql
rvm: 2.7
jobs:
  include:
    - stage: markdownlint
      node_js: 12
      script:
#        - rm -rf ~/.nvm
#        - curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
#        - sudo apt -y install nodejs
        - npm install -g markdownlint-cli
        - markdownlint *.md
    - stage: rubocop
      script:
        - bundle config set with 'development'
        - bundle install
        - bundle exec rubocop
    - stage: run tests
      script:
        - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
        - sudo apt-get -y install nodejs 
        - bundle install --without development
        - psql -c 'create database wrata_test;' -U postgres
        - RAILS_ENV=test bundle exec rake db:create db:migrate db:seed
        - bundle exec rake
    - stage: Default docker build
      script: docker build .
