instance_eval(File.read('../SharedFunctional/Gemfile'))

gem 'actionpack-action_caching'
gem 'actionpack-page_caching'
gem 'activeadmin', git: 'https://github.com/gregbell/active_admin.git'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'coffee-rails'
gem 'devise'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'magic_encoding'
gem 'pg'
gem 'protected_attributes'
gem 'puma'
gem 'rails'
gem 'rails-observers'
gem 'ransack'
gem 'resque', git: 'https://github.com/resque/resque.git', branch: '1-x-stable'
gem 'sass-rails'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'
