source 'https://rubygems.org'

gem 'actionpack-action_caching'
gem 'actionpack-page_caching'
gem 'bootbox-rails'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'coffee-rails'
gem 'devise'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'magic_encoding'
gem 'onlyoffice_digitalocean_wrapper', git: 'https://github.com/onlyoffice-testing-robot/onlyoffice_digitalocean_wrapper'
gem 'onlyoffice_rspec_result_parser', git: 'https://github.com/onlyoffice-testing-robot/onlyoffice_rspec_result_parser'
gem 'pg'
gem 'process_exists'
gem 'protected_attributes'
gem 'puma'
gem 'rails', '~> 4.2.1'
gem 'rails-observers'
gem 'ransack'
gem 'sass-rails'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
end
