version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: tests
          command: bundle exec rake test
