DOCS_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/OnlineDocuments"
TEAMLAB_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/TeamLab"
DOCS_TESTS_PATH = "/#{ENV['HOME']}/RubymineProjects/OnlineDocuments/spec"
TEAMLAB_TESTS_PATH = "/#{ENV['HOME']}/RubymineProjects/TeamLab/Rspec"
SERVERS_LOGS_PATH = 'app/server/logs'
DOCS_PROJECT_NAME = 'OnlineDocuments'
TEAMLAB_PROJECT_NAME = 'TeamLab'
DOCS_PATH_WITHOUT_HOME = '~/RubymineProjects/OnlineDocuments'
TEAMLAB_PATH_WITHOUT_HOME = '~/RubymineProjects/TeamLab'
HOME_DIRECTORY = "/#{ENV['HOME']}"
RUBYMINE_PROJECTS_PATH = "/#{ENV['HOME']}/RubymineProjects"
TEAMLAB_DEFAULT_BRANCH = 'develop'
DOCS_DEFAULT_BRANCH = 'develop'
TEAMLAB_INFO_MAIN_BRANCH = 'develop'
TEAMLAB_COM_MAIN_BRANCH = 'master'
TM_API_DEFAULT = 'develop'
DOCS_TAB_NAME = 'docs'
TEAMLAB_TAB_NAME = 'teamlab'
GUEST_NAME = 'Guest'
DEFAULT_CURRENT_TEST = 'nothing'
DEFAULT_RUN_CLIENT = 'nobody'
SUCCESS_TEST_STR = ' 0 failures'
INFO_SERVER = 'info'
COM_SERVER = 'com'
EMPTY_STRING = ''
TIME_FOR_UPDATE = 15
REGION_LIST = ['info us', 'info eu', 'info sg', 'com us', 'com eu', 'com sg', 'com org', 'default']
DEFAULT_REGION = 'default'
SECURITY_PASSWORD = 'All love wheel'
TIMEOUT_SERVER_SELFDESTROY = 5 * 60
