DOCS_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/OnlineDocuments".freeze
TEAMLAB_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/TeamLab".freeze
SERVERS_LOGS_PATH = 'app/server/logs'.freeze
DOCS_PROJECT_NAME = 'OnlineDocuments'.freeze
TEAMLAB_PROJECT_NAME = 'TeamLab'.freeze
DOCS_PATH_WITHOUT_HOME = '~/RubymineProjects/OnlineDocuments'.freeze
TEAMLAB_PATH_WITHOUT_HOME = '~/RubymineProjects/TeamLab'.freeze
HOME_DIRECTORY = "/#{ENV['HOME']}".freeze
RUBYMINE_PROJECTS_PATH = "/#{ENV['HOME']}/RubymineProjects".freeze
TEAMLAB_DEFAULT_BRANCH = 'develop'.freeze
DOCS_DEFAULT_BRANCH = 'develop'.freeze
TEAMLAB_INFO_MAIN_BRANCH = 'develop'.freeze
TEAMLAB_COM_MAIN_BRANCH = 'master'.freeze
DOCS_TAB_NAME = 'docs'.freeze
TEAMLAB_TAB_NAME = 'teamlab'.freeze
GUEST_NAME = 'Guest'.freeze
DEFAULT_CURRENT_TEST = 'nothing'.freeze
DEFAULT_RUN_CLIENT = 'nobody'.freeze
SUCCESS_TEST_STR = ' 0 failures'.freeze
INFO_SERVER = 'info'.freeze
COM_SERVER = 'com'.freeze
EMPTY_STRING = ''.freeze
TIME_FOR_UPDATE = 15
REGION_LIST = ['info us', 'info eu', 'info sg', 'com us', 'com eu', 'com sg', 'com org', 'default', 'custom'].freeze
DEFAULT_REGION = 'default'.freeze
SECURITY_PASSWORD = 'All love wheel'.freeze
TIMEOUT_SERVER_SELFDESTROY = 60 * 60
