DOCS_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/OnlineDocuments"
TEAMLAB_PROJECT_PATH = "/#{ENV['HOME']}/RubymineProjects/TeamLab"
DOCS_TESTS_PATH = "/#{ENV['HOME']}/RubymineProjects/OnlineDocuments/RspecTest"
TEAMLAB_TESTS_PATH = "/#{ENV['HOME']}/RubymineProjects/TeamLab/Rspec"
SERVERS_LOGS_PATH = "#{ENV['HOME']}/RubymineProjects/runner/app/server/logs"
DOCS_PROJECT_NAME = 'OnlineDocuments'
TEAMLAB_PROJECT_NAME = 'TeamLab'
DOCS_PATH_WITHOUT_HOME = '~/RubymineProjects/OnlineDocuments'
TEAMLAB_PATH_WITHOUT_HOME = '~/RubymineProjects/TeamLab'
HOME_DIRECTORY ="/#{ENV['HOME']}"
RUBYMINE_PROJECTS_PATH = "/#{ENV['HOME']}/RubymineProjects"
TEAMLAB_DEFAULT_BRANCH = 'master'
DOCS_DEFAULT_BRANCH = 'develop'
TEAMLAB_INFO_MAIN_BRANCH = 'develop'
TEAMLAB_COM_MAIN_BRANCH = 'develop'
TM_API_DEFAULT = 'develop'
DOCS_TAB_NAME = 'docs'
TEAMLAB_TAB_NAME = 'teamlab'
AMAZON_SERVER_NAME = 'amazon'
GUEST_NAME = 'Guest'
DEFAULT_CURRENT_TEST = 'nothing'
DEFAULT_RUN_CLIENT = 'nobody'
AMAZON_CLIENTS = ['shockwavenn']
IGNORED_MACHINES = []#['nct-at2', 'nct-at4']
SUCCESS_TEST_STR = ' 0 failures'
INFO_SERVER = 'info'
COM_SERVER = 'com'
EMPTY_STRING = ''

