# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SpecLanguagesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # SpecLanguage. As you add validations to SpecLanguage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpecLanguagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all spec_languages as @spec_languages' do
      spec_language = SpecLanguage.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:spec_languages)).to eq([spec_language])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested spec_language as @spec_language' do
      spec_language = SpecLanguage.create! valid_attributes
      get :show, params: { id: spec_language.to_param }, session: valid_session
      expect(assigns(:spec_language)).to eq(spec_language)
    end
  end

  describe 'GET #new' do
    it 'assigns a new spec_language as @spec_language' do
      get :new, params: {}, session: valid_session
      expect(assigns(:spec_language)).to be_a(SpecLanguage)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested spec_language as @spec_language' do
      spec_language = SpecLanguage.create! valid_attributes
      get :edit, params: { id: spec_language.to_param }, session: valid_session
      expect(assigns(:spec_language)).to eq(spec_language)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new SpecLanguage' do
        expect do
          post :create, params: { spec_language: valid_attributes }, session: valid_session
        end.to change(SpecLanguage, :count).by(1)
      end

      it 'assigns a newly created spec_language as @spec_language' do
        post :create, params: { spec_language: valid_attributes }, session: valid_session
        expect(assigns(:spec_language)).to be_a(SpecLanguage)
        expect(assigns(:spec_language)).to be_persisted
      end

      it 'redirects to the created spec_language' do
        post :create, params: { spec_language: valid_attributes }, session: valid_session
        expect(response).to redirect_to(SpecLanguage.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved spec_language as @spec_language' do
        post :create, params: { spec_language: invalid_attributes }, session: valid_session
        expect(assigns(:spec_language)).to be_a_new(SpecLanguage)
      end

      it "re-renders the 'new' template" do
        post :create, params: { spec_language: invalid_attributes }, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested spec_language' do
        spec_language = SpecLanguage.create! valid_attributes
        put :update, params: { id: spec_language.to_param, spec_language: new_attributes }, session: valid_session
        spec_language.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested spec_language as @spec_language' do
        spec_language = SpecLanguage.create! valid_attributes
        put :update, params: { id: spec_language.to_param, spec_language: valid_attributes }, session: valid_session
        expect(assigns(:spec_language)).to eq(spec_language)
      end

      it 'redirects to the spec_language' do
        spec_language = SpecLanguage.create! valid_attributes
        put :update, params: { id: spec_language.to_param, spec_language: valid_attributes }, session: valid_session
        expect(response).to redirect_to(spec_language)
      end
    end

    context 'with invalid params' do
      it 'assigns the spec_language as @spec_language' do
        spec_language = SpecLanguage.create! valid_attributes
        put :update, params: { id: spec_language.to_param, spec_language: invalid_attributes }, session: valid_session
        expect(assigns(:spec_language)).to eq(spec_language)
      end

      it "re-renders the 'edit' template" do
        spec_language = SpecLanguage.create! valid_attributes
        put :update, params: { id: spec_language.to_param, spec_language: invalid_attributes }, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested spec_language' do
      spec_language = SpecLanguage.create! valid_attributes
      expect do
        delete :destroy, params: { id: spec_language.to_param }, session: valid_session
      end.to change(SpecLanguage, :count).by(-1)
    end

    it 'redirects to the spec_languages list' do
      spec_language = SpecLanguage.create! valid_attributes
      delete :destroy, params: { id: spec_language.to_param }, session: valid_session
      expect(response).to redirect_to(spec_languages_url)
    end
  end
end
