name: check
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: [ 2.7 ]
        allow-failures: [ false ]
#        include:
#          - ruby: head
#            allow-failures: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup postgresql
        run: |
          sudo apt-get -y install postgresql libpq-dev
          sudo service postgresql start
          psql -h localhost -U postgres -p 5432 -c 'create database wrata_test;'
      - name: Setup dependencies
        run: |
          gem install bundler
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          RAILS_ENV=test bundle exec rake db:create db:migrate db:seed
          bundle exec rake
#  docker-build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build docker image
#        run: docker build .
#  markdownlint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#      - name: markdownlint check
#        run: |
#          npm install -g markdownlint-cli
#          markdownlint *.md
#  rubocop:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Ruby 2.7
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#      - name: Setup rubocop
#        run: |
#          bundle config set with 'development'
#          bundle install
#      - name: Run Rubocop
#        run: rubocop
