name: check
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        ruby: [ 2.7 ]
        allow-failures: [ false ]
#        include:
#          - ruby: head
#            allow-failures: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          gem install bundler
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3
          psql -h $POSTGRES_HOST -U postgres -p $POSTGRES_PORT -c 'create database wrata_test;'
          RAILS_ENV=test bundle exec rake db:create db:migrate db:seed
          bundle exec rake
#  docker-build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build docker image
#        run: docker build .
#  markdownlint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#      - name: markdownlint check
#        run: |
#          npm install -g markdownlint-cli
#          markdownlint *.md
#  rubocop:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Ruby 2.7
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#      - name: Setup rubocop
#        run: |
#          bundle config set with 'development'
#          bundle install
#      - name: Run Rubocop
#        run: rubocop
